# Generated by Django 3.0.8 on 2020-08-21 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_auto_20200514_0154'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='brch',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
