# Generated by Django 3.0.8 on 2020-09-03 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_signup_brch'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='brch',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
