# Generated by Django 3.0.8 on 2020-09-06 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_notes_brch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstn', models.CharField(max_length=10, null=True)),
                ('lastn', models.CharField(max_length=10, null=True)),
                ('email', models.CharField(max_length=10, null=True)),
                ('pass1', models.CharField(max_length=15, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='notes',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='notes.Users'),
        ),
        migrations.AlterField(
            model_name='signup',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='notes.Users'),
        ),
    ]
